spring:
  application:
    name: margin-limit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/margin_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # We strictly use Flyway to manage the schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true